


export const POST_SIGNIN_REQUEST = "POST_SIGNIN_REQUEST";
export const POST_SIGNIN_SUCCESS = "POST_SIGNIN_SUCCESS";
export const POST_SIGNIN_FAILURE = "POST_SIGNIN_FAILURE";


export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const SET_LOGIN_REQUEST = "SET_LOGIN_REQUEST";

export const SET_LOGOUT_REQUEST = "SET_LOGOUT_REQUEST";



