export const GET_PRODUCT_DATA_REQUEST = "GET_PRODUCT_DATA_REQUEST";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";

export const GET_CAROSELS_DATA_REQUEST = "GET_CAROSELS_DATA_REQUEST";
export const GET_CAROSELS_DATA_SUCCESS = "GET_CAROSELS_DATA_SUCCESS";
export const GET_CAROSELS_DATA_FAILURE = "GET_CAROSELS_DATA_FAILURE";
